name: Build Package

on:
  workflow_dispatch:
    inputs:
      package:
        required: true
        description: 'package to build'

jobs:
  buildpackage:
    strategy:
      matrix:
        arch: [amd64,arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.arch }}
      - uses: actions/checkout@v3
        with:
          repository: eweOS/packages
          ref: ${{ github.event.inputs.package }}
        
      - name: Run in Docker
        run: |
          docker run \
            --rm \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            --platform linux/${{ matrix.arch }} \
            ghcr.io/eweos/docker:buildenv \
            makepkg -s --noconfirm
