name: Check PKGBUILD using namcap

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'package to check'

jobs:
  namcapcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: eweOS/packages
          ref: ${{ github.event.inputs.package }}
      - name: Run namcap
        run: >-
          docker run
          --rm
          -v $(pwd):/${{ github.workspace }}
          -w ${{ github.workspace }}
          archlinux:latest
          bash -c "
          pacman -Sy --noconfirm namcap &&
          echo namcap result for ${{ github.event.inputs.package }} > namcap.log
          namcap ./PKGBUILD 2>&1 | tee namcap.log &&
          set -euo pipefail &&
          grep -vz ' E: ' namcap.log
          "
