name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eweos/docker:master
    steps:
      - name: Install archversion
        run: |
          pacman -Sy
          pacman -S --noconfirm archversion wget rsync
          pip install pyxdg
      - name: Fetch package check rules
        run: |
          mkdir -p ~/.config/archversion
          wget https://gist.githubusercontent.com/YukariChiba/3ec2207ad5cbfef2a3b7e4587eb66cd2/raw/d84e522efb1b6c0de7b885635240f549a62c6760/updater.ini -O ~/.config/archversion/packages.conf
      - name: Check for updates (demo)
        run: archversion check pacman
      - name: Collect result
        run: |
          mkdir -p ~/checkresult ~/.cache/archversion
          touch ~/.cache/archversion/packages.cache
          cp ~/.cache/archversion/packages.cache ~/checkresult/result.json
      - name: Deploy result
        run: |
          cd ~/checkresult
          git init
          git config --global user.name 'eweOS Update Checker'
          git config --global user.email 'nobody.noreply@ewe.moe'
          git add result.json
          git remote add github https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/eweOS/workflow-test
          git commit -m "Update package list"
          git push github HEAD:packages -f
